### ISSUE TITLE
eror on the start

### ISSUE THREAD

**Issue by caspervanneck** [smessie/SkyWarsReloaded#1]
'java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.SLIME_WALK2
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.Sound.valueOf(Sound.java:1) ~[spigot.jar:git-Spigot-9f26059-6aa0fa3]
        at com.walrusone.skywars.config.Config.load(Config.java:321) ~[?:?]
        at com.walrusone.skywars.config.Config.<init>(Config.java:146) ~[?:?]
        at com.walrusone.skywars.SkyWarsReloaded.onEnable(SkyWarsReloaded.java:115) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-9f26059-6aa0fa3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-9f26059-6aa0fa3]
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-9f26059-6aa0fa3]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-9f26059-6aa0fa3]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-9f26059-6aa0fa3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-9f26059-6aa0fa3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-9f26059-6aa0fa3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-9f26059-6aa0fa3]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-9f26059-6aa0fa3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-9f26059-6aa0fa3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]'

**Comment by smessie** [comment]
As described on the spigot page you must change your game sounds in the config if you are using 1.9 or up.
Change gameSounds in your config to those:
gameSounds:
  playerJoinLobby: ENTITY_SLIME_JUMP
  playerLeaveLobby: ENTITY_SLIME_ATTACK
  playerDeath: ENTITY_LIGHTNING_THUNDER
  playerWin: ENTITY_FIREWORK_LARGE_BLAST
  opChestVote: BLOCK_CHEST_OPEN
  timeVote: ENTITY_TNT_PRIMED
  weatherVote: ENTITY_SPLASH_POTION_THROW
  jumpVote: ENTITY_MAGMACUBE_JUMP

**Comment by caspervanneck** [comment]
@smessie o my bad sorry
