### ISSUE TITLE
doesnt work on latest spigot 1.13.2

### ISSUE THREAD

**Issue by YasunaMC** [smessie/SkyWarsReloaded#13]
`[18:34:19 WARN]: java.lang.ClassNotFoundException: com.walrusone.skywars.nms.v1_13_R2.NMSHandler
[18:34:19 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[18:34:19 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154)
[18:34:19 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[18:34:19 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[18:34:19 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[18:34:19 WARN]:        at java.lang.Class.forName0(Native Method)
[18:34:19 WARN]:        at java.lang.Class.forName(Unknown Source)
[18:34:19 WARN]:        at com.walrusone.skywars.SkyWarsReloaded.onEnable(SkyWarsReloaded.java:96)
[18:34:19 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[18:34:19 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[18:34:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[18:34:19 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434)
[18:34:19 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348)
[18:34:19 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584)
[18:34:19 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546)
[18:34:19 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424)
[18:34:19 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[18:34:19 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[18:34:19 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by YasunaMC** [comment]
tested with latest paperspigot same thing
