### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by steve4744** [smessie/SkyWarsReloaded#2]
Hi,

Getting this error on MC 1.12 using latest download form spigot v3.1.1

`[12:19:03 INFO]: [SkyWarsReloaded] Enabling SkyWarsReloaded v3.1.1
[12:19:03 INFO]: [SkyWarsReloaded] Loading support for v1_12_R1
[12:19:03 ERROR]: Error occurred while enabling SkyWarsReloaded v3.1.1 (Is it up to date?)
java.lang.IllegalArgumentException: MALFORMED
        at java.util.zip.ZipCoder.toString(ZipCoder.java:58) ~[?:1.8.0_72]
        at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:300) ~[?:1.8.0_72]
        at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122) ~[?:1.8.0_72]
        at com.walrusone.skywars.utilities.UnZip.unzip(UnZip.java:29) ~[?:?]
        at com.walrusone.skywars.utilities.SaveDefaultMaps.saveDefaultMaps(SaveDefaultMaps.java:20) ~[?:?]
        at com.walrusone.skywars.SkyWarsReloaded.onEnable(SkyWarsReloaded.java:140) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

There is a caves.zip which is downloaded into the plugins/SkyWardsReloaded folder which I can't open which may be the problem.

**Comment by smessie** [comment]
Change resaveDefaultMaps to fals in the config (bottom).
