### ISSUE TITLE
 error Citizens2 and skywarsreloaded

### ISSUE THREAD

**Issue by CasperVanNeck** [smessie/SkyWarsReloaded#6]
[19:21:38 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Could not pass event PlayerInteractEvent to SkyWarsReloaded v3.1.1
org.bukkit.event.EventException: null
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:75) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:955) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:536) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1806) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.EntityHuman.a(EntityHuman.java:1422) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.a(EntityHumanNPC.java:104) [Citizens.jar:?]
	at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:137) [Citizens.jar:?]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1603) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:688) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1405) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at com.walrusone.skywars.listeners.SpectatorListener.onPlayerInteract(SpectatorListener.java:334) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
	... 25 more

**Comment by smessie** [comment]
When does this happen?
And update to the latest version.

**Comment by CasperVanNeck** [comment]
on join @smessie
